#!/bin/sh

WGET=$(which wget)
WGET_OPTS="-qO -"
URL="http://ipinfo.io/ip"

AWK=$(which awk)
NIC="wlan0"

EXTIP=`$WGET $URL $WGET_OPTS`
INTIP=`ip addr show $NIC| $AWK '$1 == "inet" {gsub(/\/.*$/, "", $2); print $2}'`


echo "Internal: $INTIP"
echo "External: $EXTIP"
exit 0
