#!/bin/bash
cd /home/codeasm/Projects/Emulation/Windows
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    -cd|--cdrom)
    CD="$2"
    shift; shift # past argument and value
    ;;-m|--memory|-mem)
    MEM="$2" 
    shift; shift # past argument and value
    ;;-n|--net|-net)
    NET="$2"
    shift; shift # past argument and value
    ;;-hdd|--harddisk)
    HDD="$2,format=qcow2"
    shift; shift # past argument and value
    ;;-rhdd|--realharddisk)
    HDD="$2,format=raw"
    shift; shift # past argument and value
    ;;-usb)
    USB="-usb -device usb-host,bus=usb-bus.0,hostbus=$2,hostaddr=$3"
    shift; shift; shift
    ;;kernel)
    HDD="hdd/winXP_xboxdev.qcow2"
    shift # past argument and value
    ;;xbox)
    HDD="hdd/XDEV.qcow2"
    shift # past argument and value
    ;;kd) 
    SERIAL="-serial tcp::9090,server,nowait"
    shift # past argument and value
    ;;311|dos)
    HDD="hdd/dos.qcow2"
    SOUND="-machine pc,pcspk-audiodev=alsa -device sb16,audiodev=alsa -device adlib,audiodev=alsa"
    NET="-net nic,model=ne2k_pci,macaddr=E4:1F:13:AD:D5:02 -net tap,ifname=tap0,script=no"
    MEM="16"
    MOUSE="-device vmware-svga"
    shift # past argument and value
    ;;2000)
    HDD="hdd/CISCO.qcow2"
    SOUND="-machine pc,pcspk-audiodev=alsa -device adlib,audiodev=alsa -device sb16,audiodev=alsa"
    NET="-net nic,model=rtl8139,macaddr=E4:1F:13:AD:D5:02 -net tap,ifname=tap0,script=no"
    MEM="64"
    MOUSE="-vga cirrus"
    shift # past argument and value
    ;;-e|--extra|-extra)
    EXTRA="$2"
    shift; shift
    ;;games)
    HDD="hdd/win-games.qcow2"
    MEM="2G"
    shift; shift # past argument and value
    ;;
esac
done


if [ ${name+MEM} ]; then
    MEM="2G"; fi
if [ ${name+NET} ]; then
    #NET="-net nic,model=rtl8139 -net user,smb=/home/codeasm/Projects/Emulation/smb/win "; fi
    NET=" -net nic,model=rtl8139,macaddr=E4:1F:13:AD:D5:02 -net tap,ifname=tap0,script=no "; fi
if [ $CD ]; then
    CDfull="-cdrom ""${CD}"" -boot d"; fi
if [ -z $HDD ]; then
    HDD="hdd/GAMES.qcow2"; fi
# -device ES1370
if [ ${name+SOUND} ]; then
    SOUND="-device AC97,audiodev=alsa"; fi
if [ ${name+VID} ]; then
    VID="-display sdl -vga std"; fi
if [ ${name+MOUSE} ]; then
    MOUSE="-device usb-ehci,id=ehci -device usb-mouse,bus=usb-bus.0"; fi

if [ $CD ]; then    
printf "ISO is \t\t %s" ${CD}; fi
printf "\n\rMemory size \t\t %s" ${MEM}
printf "\n\rHarddisk \t\t %s" ${HDD}
#printf "\n\rSoundcard \t\t %s" ${SOUND}
printf "\n"

# -enable-kvm
# -smp 2 -cpu host 
qemu-system-i386 -m size=${MEM}    \
    -drive file=${HDD}             \
    -audiodev id=alsa,driver=alsa  \
    ${NET} ${VID}                  \
    -usb -monitor stdio            \
    $MOUSE                         \
    ${SOUND}                       \
    ${SERIAL} ${USB} ${CDfull}     \
    ${EXTRA}                       \

    
## Resources used
## 
## https://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash
