#!/bin/bash
cd /home/codeasm/Projects/Emulation/Windows
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    -cd|--cdrom)
    CD="$2"
    shift; shift # past argument and value
    ;;-m|--memory|-mem)
    MEM="$2"
    shift; shift # past argument and value
    ;;-n|--net|-net)
    NET="$2"
    shift; shift # past argument and value
    ;;-hdd|--harddisk)
    HDD="$2"
    shift; shift # past argument and value
    ;;-usb)
    USB="-usb -device usb-host,bus=usb-bus.0,hostbus=2,hostaddr=$2"
    shift; shift
    ;;kernel)
    HDD="hdd/winXP_xboxdev.qcow2"
    shift # past argument and value
    ;;xbox)
    HDD="hdd/XDEV.qcow2"
    shift # past argument and value
    ;;kd) 
    SERIAL="-serial tcp::9090,server,nowait"
    shift # past argument and value
    ;;311|dos)
    HDD="hdd/dos.qcow2"
    NET="-soundhw sb16,adlib,pcspk"
    MEM="16"
    shift # past argument and value
    ;;games)
    HDD="hdd/win-games.qcow2"
    MEM="2G"
    shift; shift # past argument and value
    ;;
esac
done


if [ -z $MEM ]; then
    MEM="2G"; fi
if [ -z $NET ]; then
    #NET="-net nic,model=rtl8139 -net user,smb=/home/codeasm/Projects/Emulation/smb/win "; fi
    NET=" -net nic,model=rtl8139,macaddr=E4:1F:13:AD:D5:02 -net tap,ifname=tap0,script=no "; fi
if [ $CD ]; then
    CDfull="-cdrom ""${CD}"" -boot d"; fi
if [ -z $HDD ]; then
    HDD="hdd/GAMES.qcow2"; fi
# -device ES1370
if [ -z $SOUND ]; then
    SOUND="-device AC97"; fi
 

if [ $CD ]; then    
printf "ISO is \t\t %s" ${CD}; fi
printf "\n\rMemory size \t\t %s" ${MEM}
printf "\n\rHarddisk \t\t %s" ${HDD}
printf "\n\rSoundcard \t\t %s" ${SOUND}
printf "\n"

qemu-system-i386 -enable-kvm -m size=${MEM}     \
    -smp 2 -cpu host                            \
    -drive file=${HDD},format=qcow2             \
    ${NET} -sdl -vga std                        \
    -device vt82c686b-usb-uhci,id=uhci          \
    -device usb-mouse,bus=uhci.0                \
    ${SOUND}                                    \
    ${SERIAL} ${USB} ${CDfull}                  \
