#!/bin/bash
cd /home/codeasm/xqemu
#QEMU_ALSA_SAMPLES=2048 #4096 #128
#QEMU_AUDIO_DRV=alsa
#AUDIODEV=hw

if [ $1 = "chihiro" ]; then
xqemu-git/xbox-softmmu/qemu-system-xbox -cpu pentium3 -machine chihiro,mediaboard_rom=bios/mediaboard_rom.bin -m 128 -bios bios/chihiro_bios.bin
elif [ $1 = "mu" ]; then
xqemu-git/xbox-softmmu/qemu-system-xbox -cpu pentium3 -machine xbox,short_animation,bootrom=mcpx/mcpx_1.0.bin -m 64 -drive file=harddisk/xboxlive.qcow2,index=0,media=disk,locked=on -drive index=1,media=cdrom -bios bios/old/complex_4627debug.bin -drive if=none,id=stick,file=harddisk/mu.raw -drive if=none,id=stick2,file=harddisk/mu2.raw -usb -device usb-hub,bus=usb-bus.0,port=3 -device usb-xbox-gamepad,bus=usb-bus.0,port=3.2 -device usb-storage,bus=usb-bus.0,port=3.3,drive=stick -device usb-storage,bus=usb-bus.0,port=3.4,drive=stick2
elif [ $1 = "usb" ]; then
if [ $3 = "cd" ]; then
xqemu-git/xbox-softmmu/qemu-system-xbox -cpu pentium3 -machine xbox,short_animation,bootrom=mcpx/mcpx_1.0.bin -m 64 -drive file=harddisk/xboxlive.qcow2,index=0,media=disk,locked=on -drive file=$4,index=1,media=cdrom -bios bios/old/complex_4627debug.bin -drive if=none,id=stick,file=$2 -usb -device usb-hub,bus=usb-bus.0,port=3 -device usb-xbox-gamepad,bus=usb-bus.0,port=3.2 -device usb-storage,bus=usb-bus.0,port=3.3,drive=stick
else
xqemu-git/xbox-softmmu/qemu-system-xbox -cpu pentium3 -machine xbox,short_animation,bootrom=mcpx/mcpx_1.0.bin -m 64 -drive file=harddisk/xboxlive.qcow2,index=0,media=disk,locked=on -drive index=1,media=cdrom -bios bios/old/complex_4627debug.bin -drive if=none,id=stick,file=$2 -usb -device usb-hub,bus=usb-bus.0,port=3 -device usb-xbox-gamepad,bus=usb-bus.0,port=3.2 -device usb-storage,bus=usb-bus.0,port=3.3,drive=stick
fi
elif [ $1 = "network" ]; then
xqemu-git/xbox-softmmu/qemu-system-xbox -cpu pentium3 -machine xbox,short_animation,bootrom=mcpx/mcpx_1.0.bin -m 64 -drive file=harddisk/xboxlive.qcow2,index=0,media=disk,locked=on -drive index=1,media=cdrom -bios bios/old/complex_4627debug.bin -drive if=none,id=stick,file=harddisk/mu.raw -drive if=none,id=stick2,file=harddisk/mu2.raw -usb -device usb-hub,bus=usb-bus.0,port=3 -device usb-xbox-gamepad,bus=usb-bus.0,port=3.2 -device usb-storage,bus=usb-bus.0,port=3.3,drive=stick -device usb-storage,bus=usb-bus.0,port=3.4,drive=stick2 -global nvnet.dump=xbox_net_packets.txt -net nic,model=nvnet -net user -net socket,listen=:1236 
elif [ $1 = "hd" ]; then
if [ $3 = "cd" ]; then
xqemu-git/xbox-softmmu/qemu-system-xbox -cpu pentium3 -machine xbox,short_animation,bootrom=mcpx/mcpx_1.0.bin -m 64 -drive file=$2,index=0,media=disk,locked=on -drive file=$4,index=1,media=cdrom -bios bios/old/complex_4627debug.bin -usb -device usb-hub,bus=usb-bus.0,port=3 -device usb-xbox-gamepad,bus=usb-bus.0,port=3.2  -device lpc47m157 -serial unix:/tmp/xserial,server
else
xqemu-git/xbox-softmmu/qemu-system-xbox -cpu pentium3 -machine xbox,short_animation,bootrom=mcpx/mcpx_1.0.bin -m 64 -drive file=$2,index=0,media=disk,locked=on -drive index=1,media=cdrom -bios bios/old/complex_4627debug.bin -usb -device usb-hub,bus=usb-bus.0,port=3 -device usb-xbox-gamepad,bus=usb-bus.0,port=3.2 
fi
elif [ $1 = "cd" ]; then
xqemu-git/xbox-softmmu/qemu-system-xbox -cpu pentium3 -machine xbox,short_animation,bootrom=mcpx/mcpx_1.0.bin -m 64 -drive file=harddisk/xbox_harddisk.qcow2,index=0,media=disk,locked=on -drive file=$2,index=1,media=cdrom -bios bios/old/complex_4627debug.bin -usb -device usb-hub,bus=usb-bus.0,port=1 -device usb-xbox-gamepad,bus=usb-bus.0,port=1.2 
elif [ $1 = "dev" ]; then
xqemu/xbox-softmmu/qemu-system-xbox -cpu pentium3 -machine xbox,short_animation,bootrom=mcpx/mcpx_1.0.bin -m 128 -drive file=harddisk/xbox_dev.qcow2,index=0,media=disk,locked=on -drive file=$2,index=1,media=cdrom -bios bios/old/complex_4627debug.bin -usb -device usb-hub,bus=usb-bus.0,port=3 -device usb-xbox-gamepad,bus=usb-bus.0,port=3.2
elif [ $1 = "update" ]; then
xqemu-git/xbox-softmmu/qemu-system-xbox -cpu pentium3 -machine xbox,short_animation,bootrom=mcpx/mcpx_1.1.bin -m 64 -drive file=harddisk/xbox2.qcow2,index=0,media=disk,locked=on -drive file=$2,index=1,media=cdrom -bios bios/EvoxM7_ef_huge-g_red.bin -usb -device usb-hub,bus=usb-bus.0,port=3 -device usb-xbox-gamepad,bus=usb-bus.0,port=3.2
elif [ $1 = "audio" ]; then
xqemu-audio/xbox-softmmu/qemu-system-xbox -cpu pentium3 -machine xbox,short_animation,bootrom=mcpx/mcpx_1.0.bin -m 64 -drive file=harddisk/xbox_harddisk.qcow2,index=0,media=disk,locked=on -drive file=$2,index=1,media=cdrom -bios bios/4627.bin -usb -device usb-hub,bus=usb-bus.0,port=3 -device usb-xbox-gamepad,bus=usb-bus.0,port=3.2 -S -s 
elif [ $1 = "mcpx" ]; then
xqemu-git/xbox-softmmu/qemu-system-xbox -cpu pentium3 -machine xbox,short_animation,bootrom=mcpx/mcpx_1.1.bin -m 64 -drive file=harddisk/xbox_harddisk.qcow2,index=0,media=disk,locked=on -drive file=$2,index=1,media=cdrom -bios bios/EvoxM7_ef_huge-g_red.bin -usb -device usb-hub,bus=usb-bus.0,port=3 -device usb-xbox-gamepad,bus=usb-bus.0,port=3.2
elif [ $1 = "con" ]; then
xqemu-git/xbox-softmmu/qemu-system-xbox -cpu pentium3 -machine xbox,short_animation,bootrom=mcpx/mcpx_1.1.bin -m 64 -drive file=harddisk/xbox_harddisk.qcow2,index=0,media=disk,locked=on -drive file=$2,index=1,media=cdrom -bios bios/EvoxM7_ef_huge-g_red.bin -usb -device usb-host,bus=usb-bus.0,port=3,vendorid=0x45e,productid=0x28e
elif [ $1 = "net" ]; then
xqemu-git/xbox-softmmu/qemu-system-xbox -cpu pentium3 -machine xbox,short_animation,bootrom=mcpx/mcpx_1.0.bin -m 128 -drive file=harddisk/xboxlive.qcow2,index=0,media=disk,locked=on -drive index=1,media=cdrom -bios bios/old/complex_4627debug.bin -usb -device usb-hub,bus=usb-bus.0,port=3 -device usb-xbox-gamepad,bus=usb-bus.0,port=3.2 -global nvnet.dump=xbox_net_packets_multi.txt -net nic,model=nvnet -net user -net socket,connect=127.0.0.1:8010 
elif [ $1 = "dvt4" ]; then
xqemu/xbox-softmmu/qemu-system-xbox -cpu pentium3 -machine xbox,short_animation,bootrom=mcpx/mcpx_1.0.bin -m 128 -drive file=harddisk/xbox_devkit.qcow2,index=0,media=disk,locked=on -drive file=$2,index=1,media=cdrom -bios bios/old/complex_4627debug.bin -usb -device usb-hub,bus=usb-bus.0,port=3 -device usb-xbox-gamepad,bus=usb-bus.0,port=3.2
else
xqemu-git/xbox-softmmu/qemu-system-xbox -cpu pentium3 -machine xbox,short_animation,bootrom=mcpx/mcpx_1.0.bin -m 64 -drive file=harddisk/xbox_harddisk.qcow2,index=0,media=disk,locked=on -drive index=1,media=cdrom -bios bios/old/complex_4627debug.bin -usb -device usb-hub,bus=usb-bus.0,port=3 -device usb-xbox-gamepad,bus=usb-bus.0,port=3.2 
fi
