#!/bin/bash
cd /home/codeasm/Games/Xbox/
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    -cd|--cdrom|-iso)
    CD="$2"
    shift; shift # past argument and value
    ;;-d|debug)
    MONITOR="-S -s"
    shift; # past argument and value
    ;;-bios|-kernel|-k)
    KERNEL="$2"
    shift; shift # past argument and value
    ;;-m|--memory|-mem)
    MEM="$2"
    shift; shift # past argument and value
    ;;-hdd|--harddisk)
    HDD="$2"
    shift; shift # past argument and value
    ;;-mu|-memoryunit)
    MU="-drive if=none,id=C1A,file=$2,format=raw -device usb-storage,port=3.2,drive=C1A"
    shift; shift # past argument and value
    ;;-mcpx|--mcpx)
    MCPX="$2"
    shift; shift # past argument and value
    ;;-net|--network)
    NET="$2"
    shift; shift # past argument and value
    ;;-dev|-devkit|-debug)
    NET="-net nic,model=nvnet -net tap,ifname=tap0,script=no"
    shift; # past argument 
    ;;-eeprom|-e)
    EEPROM="-eeprom $2"
    shift; shift # past argument and value
    ;;-monitor|-mon)
    MONITOR="-chardev stdio,mux=on,id=char0 -mon chardev=char0,mode=readline "
    shift; # past argument
     ;;-kd|--kerneldebug)
    KD="-device lpc47m157 -serial unix:/tmp/xserial,server"
    shift;# past argument and value
     ;;-kdxp|-fullkd)
    KD="-device lpc47m157 -serial tcp:127.0.0.1:9090"
    shift;# past argument and value
    ;;-usb|-4400)
    USB="-usb -device usb-xbox-gamepad,bus=usb-bus.0"
    shift; # past argument and value
    ;;-ftp)
    EEPROM="-net nic -net user,hostfwd=tcp::2220-:21"
    shift; # past argument and value
    ;;
esac
done

if [ -z $KERNEL ]; then
    KERNEL="bios/complex_4627debug.bin"; fi
if [ -z $HDD ]; then
    HDD="harddisk/xbox_harddisk.qcow2"; fi
if [ -z $MCPX ]; then
    MCPX="mcpx/mcpx_1.0.bin"; fi
if [ -z $MEM ]; then
    MEM="64"; fi
if [ $CD ]; then
    CDfull="file=""${CD}"","; fi
if [ -z $USB ]; then    
     USB=""; fi

printf "Xbox dvd-disk \t\t %s" ${CD}
printf "\n\rKernel/Bios \t\t %s" ${KERNEL}
printf "\n\rMemory size \t\t %s" ${MEM}
printf "\n\rMCPX version \t\t %s" ${MCPX}
printf "\n\rHarddisk \t\t %s" ${HDD}
printf "\n\rUSB \t\t %s" ${USB}
printf "\n\rMemory unit \t\t %s" "${MU}"
printf "\n\rMonitor if set is \t\t %s" "${MONITOR}"


printf "\n\r-----------------------------\n\r"

xqemu/i386-softmmu/qemu-system-i386 \
-cpu pentium3 -machine xbox,short_animation,bootrom=${MCPX} \
-m ${MEM} -drive file=${HDD},index=0,media=disk,locked=on \
-drive ${CDfull}index=1,media=cdrom -bios ${KERNEL} ${KD} \
-device usb-hub,port=3 -usb -device usb-xbox-gamepad,port=3.1 ${MU} ${EEPROM} ${MONITOR} ${NET} \
-usb -device usb-host,vendorid=0x090c,productid=0x1000,bus=usb-bus.0,port=3
